# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-02 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custommer', '0002_auto_20190201_0435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custommer_code', models.IntegerField()),
                ('razon', models.CharField(max_length=100)),
                ('custommer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custommer.Custommer')),
            ],
        ),
    ]
