# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-03 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custommer', '0003_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='razon',
            new_name='reazon',
        ),
    ]
